import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./provider";
import { fonts } from "./fonts";
import { Center } from "@chakra-ui/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={fonts.rubik.variable}>
      <body>
        <Providers>
          <Center as="main">{children}</Center>
        </Providers>
      </body>
    </html>
  );
}
